#!/bin/bash
# downloads all vim plugins into the bundle folder


echo "Downloading plugins"

DIRECTORY=bundle

if [ -d "$DIRECTORY" ]; then 
	echo "Directory Exists";
else
	echo "Creating Bundle Directory";
	mkdir bundle
fi

GITHEADER="https://github.com/"
GITFOOTER=".git"
PLUGINS=($(grep -v "\"Plugin" plugins.vim| grep -w "Plugin" | tr -d \' | cut -b 1-7 --complement))
cd bundle
echo "Cloning Plugins..."
for PLUGIN in "${PLUGINS[@]}"; do
	echo "$GITHEADER$PLUGIN$GITFOOTER"
	git clone "$GITHEADER$PLUGIN$GITFOOTER"
done
echo "Done!"
